---
name: Docker Build master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone latest repository
        uses: actions/checkout@v2
      - name: Build dex container image and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'ghcr.io/hathitrust/dex-shib-proxy-unstable:${{ github.sha }},ghcr.io/hathitrust/dex-shib-proxy-unstable:latest'
          file: Dockerfile
