name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to Production
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/hathitrust/dex-shib-proxy:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }}
        cluster_server: ${{ secrets.KUBERNETES_SERVER }}
        namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
        resource_type: deployment
        resource_name: oidc-saml-proxy-dex
        container: dex
