---
name: Docker Tag Latest Release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone latest repository
        uses: actions/checkout@v2
      - name: Tag latest release in GHCR
        run: |
          docker pull ghcr.io/hathitrust/dex-shib-proxy-unstable:${{ github.sha }}
          docker tag ghcr.io/hathitrust/dex-shib-proxy-unstable:${{ github.sha }} ghcr.io/hathitrust/dex-shib-proxy:${{ github.event.release.tag_name }}
          docker tag ghcr.io/hathitrust/dex-shib-proxy-unstable:${{ github.sha }} ghcr.io/hathitrust/dex-shib-proxy:latest
          docker push ghcr.io/hathitrust/dex-shib-proxy:${{ github.event.release.tag_name }}
          docker push ghcr.io/hathitrust/dex-shib-proxy:latest
